#!/bin/bash
# Verify a packfile generated by MoonBit with git verify-pack
# This script takes a hex-encoded packfile from stdin and verifies it

set -e

TEST_DIR="/tmp/moonbit-packfile-verify"
rm -rf "$TEST_DIR"
mkdir -p "$TEST_DIR"

# Read hex from stdin and convert to binary
PACK_FILE="$TEST_DIR/test.pack"

# If argument provided, use it as hex data
if [ -n "$1" ]; then
    echo "$1" | xxd -r -p > "$PACK_FILE"
else
    # Read from stdin
    xxd -r -p > "$PACK_FILE"
fi

echo "Packfile size: $(wc -c < "$PACK_FILE") bytes"
echo ""
echo "Hex dump (first 64 bytes):"
xxd "$PACK_FILE" | head -4
echo ""

# Verify with git
echo "Running git verify-pack..."
if git verify-pack -v "$PACK_FILE"; then
    echo ""
    echo "✓ Packfile is valid!"
else
    echo ""
    echo "✗ Packfile verification failed"
    exit 1
fi

# Cleanup
rm -rf "$TEST_DIR"
